### ISSUE TITLE
Package ajaxorg/ace-builds not found in packagist.org

### ISSUE THREAD

**Issue by snickom** [trntv/yii2-aceeditor#17]
Problem 1
    - trntv/yii2-aceeditor 2.1.0 requires ajaxorg/ace-builds ^1.2.8 -> no matching package found.
    - trntv/yii2-aceeditor 2.1.0 requires ajaxorg/ace-builds ^1.2.8 -> no matching package found.
    - Installation request for trntv/yii2-aceeditor ~2.1.0 -> satisfiable by trntv/yii2-aceeditor[2.1.0].

**Comment by snickom** [comment]
Fix is in pull request ... https://github.com/trntv/yii2-aceeditor/pull/16

**Comment by snickom** [comment]
Thank you (fixed in dev-master).

**Comment by Galyam** [comment]
composer require trntv/yii2-aceeditor

Problem 1
    - Installation request for trntv/yii2-aceeditor dev-master -> satisfiable by trntv/yii2-aceeditor[dev-master].
    - trntv/yii2-aceeditor dev-master requires ajaxorg/ace-builds ^1.2.8 -> no matching package found.

**Comment by snickom** [comment]
1. If you have installed fxp/composer-asset-plugin globally, please remove it and use asset-packagist.com instead.

2. Sometimes asset-packagist.com go wrong and you must fetch bower-asset package via webpage  (https://asset-packagist.org/package/bower-asset/ace-builds) .
