### ISSUE TITLE
Create release on packagist.org

### ISSUE THREAD

**Issue by snickom** [trntv/yii2-aceeditor#20]
On [Packagist.org](https://packagist.org/packages/trntv/yii2-aceeditor#dev-master) are incorrectly synchronized data from [repository](https://github.com/trntv/yii2-aceeditor/blob/master/composer.json). 
Please create a new stable release and fix problem fix packagist.org. 
Thank you.

**Comment by trntv** [comment]
https://github.com/trntv/yii2-aceeditor/releases/tag/2.1.2
