### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by dellirom** [trntv/yii2-aceeditor#5]
After installation and configuration AceEditor nothing happens . 
White field where must be editor .
Please help me understand .

**Comment by trntv** [comment]
Is there any errors in console?

**Comment by dellirom** [comment]
no error in the console

**Comment by dellirom** [comment]
Sorry it's my fault . Firebag not show error. But Chrome has shown. Fixed and it worked . Thank you very much

**Comment by trntv** [comment]
you are welcome
